### ISSUE TITLE
Governance for sub-project

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#10]
This issue is to address the follows:
- Define what sub-project is.
- How to request a sub-project.
- Criteria to approve a sub-project.

**Comment by FeynmanZhou** [comment]
These process has been covered by repository lifecycle management doc: https://github.com/notaryproject/.github/blob/main/REPOSITORIES.md. I think we can close it as completed.

**Comment by yizha1** [comment]
Closed per @FeynmanZhou 's comment.
