### ISSUE TITLE
Add OWNERS for each sub-project

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#13]
The OWNERS are admin maintainers who can update/delete sub-project and create security advisories.

See the definition of roles: [Repository roles for an organization](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization)

See example, https://github.com/oras-project/oras/blob/main/OWNERS.md

**Comment by yizha1** [comment]
As clarified in another issue: CODWOWNERS and OWNERS are different. 

- CODEOWNERS are clearly defined here https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
- OWNERS means people has the `Admin` role, as defined here https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations. 

OWNERS is just an arbitrary file name. Maintainers can have both `Maintain` and `Admin` roles. In this case, there is no need to create another file of OWNERS.  We can update existing MAINTAINERS with the association of repository roles.

**Comment by toddysm** [comment]
Closing this one as per the discussion above. We don't need additional file for this information.
