### ISSUE TITLE
Notary project Teams management

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#14]
Based on the [Repository roles for organizations](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization), I propose that we create the following GitHub teams:

- Create sub-repo maintainers team, who need to manage the repository without access to sensitive or destructive actions
  - subproject-notation-maintainers
  - subproject-notation-go-maintainers
  - subproject-notation-core-go-maintainers
  - subproject-notaryproject-maintainers
  - subproject-roadmap-maintainers
  - subproject-website-maintainers
  - subproject-notes-maintainers
  - subproject-notary-maintainers
  - subproject-tuf-maintainers
- Create sub-repo admin (or owner) team, who has full access to the sub-project, including sensitive and destructive actions like managing security or deleting a repository
  - subproject-notation-owners
  - subproject-notation-go-owners
  - subproject-notation-core-go-owners
  - subproject-notaryproject-owners
  - subproject-roadmap-owners
  - subproject-website-owners
  - subproject-notes-owners
  - subproject-notary-owners
  - subproject-tuf-owners
- Create org owner team, who has full access to the whole notary project
  - notary-project-org-owners

Note:
- The code reviewers are managed by CODEOWNERS file under each sub-project. People listed in the CODEOWNERS file are automatically requested for review when someone opens a pull request that modifies code that they own.

**Comment by shizhMSFT** [comment]
I'd suggest removing the `subproject-` prefix. For instance, `@notaryproject/subproject-notation-maintainers` becomes `@notaryproject/notation-maintainers`.

**Comment by toddysm** [comment]
I agree with @shizhMSFT about the `subproject` use. Also, I am not sure what is the difference between `*-maintainers` and `*-owners`. Aren't those the same? 

We already have some of the teams available but they need to be populated with the right folks. Here is what teams are currently created:
![image](https://user-images.githubusercontent.com/1007103/225681166-763aac10-c1b2-48d6-a0c1-93c603f80231.png)

The `notaryproject-governance-maintainers` is intended for the `.github` repository. For the rest, I propose to have only single team per repo with the following convention `notaryproject-[reponame]-maintainers` and one more group for the `notaryproject-org-maintainers`.

The project is public so we don't need to complicate the user administration with other teams.

**Comment by yizha1** [comment]
Thanks @shizhMSFT @toddysm It makes sense. I agree with the proposal:

- Only single team per repo with the following convention `notaryproject-[reponame]-maintainers`, for example `notaryproject-notation-maintainers`
- One more group for the `notaryproject-org-maintainers`.

The current maintainers have both `admin` role and `maintain` role (as defined in https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations), so there is no need to create teams for owners.

**Comment by iamsamirzon** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM for creating group per repo

**Comment by toddysm** [comment]
Here are the teams that are created, and the memberships maps the corresponding MAINTAINERS file as linked below:

- notaryproject-notation-maintainers -> [Notation MAINTAINERS](https://github.com/notaryproject/notation/blob/main/MAINTAINERS)
- notaryproject-notation-go-maintainers -> [Notation-go MAINTAINERS](https://github.com/notaryproject/notation-go/blob/main/MAINTAINERS)
- notaryproject-notation-core-go-maintainers -> [Notation-core-go MAINTAINERS](https://github.com/notaryproject/notation-core-go/blob/main/MAINTAINERS)
- notaryproject-notaryproject-maintainers -> [Notaryproject MAINTAINERS](https://github.com/notaryproject/notaryproject/blob/main/MAINTAINERS)
- notaryproject-roadmap-maintainers -> [Roadmap MAINTAINERS](https://github.com/notaryproject/roadmap/blob/main/MAINTAINERS)
- notaryproject-website-maintainers -> [Website MAINTAINERS](https://github.com/notaryproject/notaryproject.dev/blob/main/MAINTAINERS)
- notaryproject-meeting-notes-maintainers -> [Meeting Notes MAINTAINERS](https://github.com/notaryproject/meeting-notes/blob/main/MAINTAINERS)
- notaryproject-notary-maintainers -> [Notary MAINTAINERS](https://github.com/notaryproject/notary/blob/master/MAINTAINERS) *NOTE:* Only the maintainers for `notary` repo or current org maintainers added to the team.
- notaryproject-tuf-maintainers -> *NOTE:* There is no MAINTAINERS file in the TUF repository as this is not completed https://github.com/notaryproject/tuf/issues/34 Used the information from [Notary MAINTAINERS](https://github.com/notaryproject/notary/blob/master/MAINTAINERS) to populate with the names for TUF repository. Only TUF maintainers from that file and current org maintainers were added

The following two are already existing:
- notaryproject-org-owners -> [Governance MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS)
- notaryproject-governance-maintainers -> [Governance MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS)

The following teams were removed from the organization:
- Notary websitre maintainers -> Replaced by notaryproject-website-maintainers
- notary-tuf-maintainers -> Replaced by notaryproject-tuf-maintainers
- notation-code-reviewers -> Not needed
- notation-release-managers -> Not needed
- notation-sub-group-maintainers -> Replaced by notaryproject-notation-maintainers

We can close this issue.

**Comment by SteveLasker** [comment]
I see the 1:1 mapping of a repo to a team. What was lost was a sub-project was mapped to multiple repos. 
For instance, a notation sub-project maintainer would have access to notation, notation-go, notation-core-go. 
This new structure requires more detailed management and nomination process as someone nominated to the notation sub-project would need to be added to 3 teams, with assumed 3 nominations. 

Was this the intent?
See this example for oras: [sub-projects.md](https://github.com/oras-project/community/blob/3f691e4d9f737e3dca0f0d0abad5274d1211db9f/sub-projects.md)

**Comment by toddysm** [comment]
> Was this the intent?
Yes, it was discussed on several occasions. The overhead is negligible compared to the level of separation of duties we are achieving. We don't change those teams on a daily basis and creating all new teams and managing the members took less than 30 mins. Further management will not require more than couple of mins per year.

**Comment by toddysm** [comment]
Closing this issue as the work is done
