### ISSUE TITLE
Create Contributor ladder document for each sub-project

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#15]
Proposal of creating contributor ladder document by referring to the template https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md

**Comment by toddysm** [comment]
Do we need that for each sub-project? Should we just have one for the whole project?

**Comment by yizha1** [comment]
> Do we need that for each sub-project? Should we just have one for the whole project?

I think we need one for the whole project unless there is a special case for some sub-projects.
