### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#19]
This issue is for describing and documenting release management, including
- Stage of development: `Alpha`, `Beta`, `Release candidate`, `stable release` 
- Release versioning
- Criteria for supported releases

The proposal is to update the document [release_management.md](https://github.com/notaryproject/notation/blob/main/RELEASE_MANAGEMENT.md).

**Comment by toddysm** [comment]
Have a PR that is open throughout the 1.0.0 release and amend with all the activities we do as part of the release. Once we are ready for announcement, we can merge the PR. We need to be very prescriptive on the - we will create the PR against the current markdown file and will update with the actual steps.

**Comment by toddysm** [comment]
@yizha1 Can you mark this as 1.0.0 item?

**Comment by yizha1** [comment]
Closed as https://github.com/notaryproject/notation/pull/714 merged
