### ISSUE TITLE
Update the notaryproject-org-maintainers with the new maintainers

### ISSUE THREAD

**Issue by toddysm** [notaryproject/.github#20]
The `notaryproject-org-maintainers` GitHub team still has only three maintainers and this is the group that is assigned to manage the organization. As per previous discussions, we would like to have the people listed in the [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) file added to that team to allow them to maintain the organization. This was discussed in #3 and the teams structure was discussed in #14.

This issue is only to provide visibility that this change will be made.

**Comment by SteveLasker** [comment]
@Toddy, how would you track votes on the individuals? As commented [here](https://github.com/notaryproject/.github/issues/3#issuecomment-1472372917), can we please do individual votes for org maintainers? 
If you'd like to do that as individual PRs, that's also good, as long as there are votes on the individuals to become org maintainers.

**Comment by toddysm** [comment]
The above work is completed. We can close.
