### ISSUE TITLE
Upload community call recording video to YouTube

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#22]
Problem: The community call recording is not uploaded to YouTube.
- The recording video of community call should be uploaded to YouTube by default for openness, transparency, and tracking purpose
- Upload the existing recordings to YouTube
- Figure out a way of automatically uploading to save effort from manual work.

**Comment by FeynmanZhou** [comment]
We got an access invitation to CNCF-related platforms a couple of days ago. It requires another CNCF email account access to log in to the Notary Zoom account. I submitted a ticket to CNCF to ask for their help and request automation for this flow. https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1684?created=true

I will update the progress here if I receive any updates from the CNCF Service Desk.

**Comment by FeynmanZhou** [comment]
Now the livestreaming to Youtube option has been set in Notary's Zoom meeting room. We can enable the livestreaming option when starting the meeting. The recordings will be automatically uploaded to Youtube. 

![image](https://user-images.githubusercontent.com/40452856/231655827-ec467f35-701a-4195-95aa-8afa01c935e0.png)

For previous meeting records, we may need to download from Zoom and upload them to YouTube manually. I am still confirming this question with CNCF.

**Comment by yizha1** [comment]
@FeynmanZhou can this issue be closed now?

**Comment by FeynmanZhou** [comment]
Yes. We can close it as the Zoom-to-Youtube livestream configuration was set. We had a guideline for streaming https://lists.cncf.io/g/cncf-notary-maintainers/topic/98852881
