### ISSUE TITLE
Refactor and migrate the release guideline

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/.github#28]
Hi @notaryproject/notaryproject-governance-maintainers @notaryproject/notaryproject-notation-maintainers ,

The [RELEASE_CHECKLIST.md](https://github.com/notaryproject/notation/blob/main/RELEASE_CHECKLIST.md) only covers a small part of the process and checklist. We need to update it by standing on the whole Notation project's point of view and involve notation-go and notation-core-go projects in this release guideline. 

I propose migrating [RELEASE_CHECKLIST.md](https://github.com/notaryproject/notation/blob/main/RELEASE_CHECKLIST.md) 
 and [RELEASE_MANAGEMENT.md](https://github.com/notaryproject/notation/blob/main/RELEASE_MANAGEMENT.md) from the Notation CLI repo to this repo and update them accordingly. Then add these two links on the Notary website.

**Comment by yizha1** [comment]
LGTM. 
There is a https://github.com/notaryproject/notation/blob/main/RELEASE_MANAGEMENT.md under notation repo, which is also linked by Readme.md in Notation repo. We need to update those parts as well. And maybe under each subproject repo, link to the "new" release management document, so that folks jumped in any of the repo can be aware of it.

**Comment by iamsamirzon** [comment]
We have a choice to make between
1.  consolidate all guidelines in one doc but create different sections within the guidelines for each of the code repository - Notation CLI, Notation-go, Notation-core-go.  Pros - No duplication;  a single place within .github repo to manage; Cons - For anything in the .github repository, the org level maintainers will have to approve any PR, which will slow down the process
2. Let each repo have its own well define release process. Pros - The maintainers of each repo can make their own decision and update their process amongst themselves. Cons - There will be some duplication.

**Comment by yizha1** [comment]
Remove from 1.1.0 milestone as it is not related to any features/bugs.
