### ISSUE TITLE
Code of Conduct cited is incorrect and out of date

### ISSUE THREAD

**Issue by TheFoxAtWork** [notaryproject/.github#29]
The Code of Conduct for this project (merged in March) is out of date and incorrect.
This project's code of conduct https://github.com/notaryproject/.github/blob/main/CODE_OF_CONDUCT.md
references 1.0 of the CoC, however this version has not been in use since 2021. [1.1 was committed on Oct 12th of 2021](https://github.com/cncf/foundation/commit/d6ac18a62211414a29d17d640717e9925f71d534), and [1.2 was committed on Jun 29th of 2022](https://github.com/cncf/foundation/commit/f87791eb685f3b05f9f5415aa713fb6f6e6b9bbe).

The correct CoC can be found at https://github.com/cncf/foundation/blob/main/code-of-conduct.md

Changes required:
* update this project's CoC to minimally match the current CNCF's CoC

Additional recommendations:
* include a link to the current CNCF CoC within this project's CoC
* maintainers engage TAG Contributor Strategy to verify the accuracy, impact, and breadth of the contents of the recent governance file updates.

**Comment by geekygirldawn** [comment]
We (TAG Contributor Strategy) would be happy to help out with this! It would be great if you could file an issue in our repo with more details about the recent updates: https://github.com/cncf/tag-contributor-strategy/issues 

You can also drop into our Slack Channel or any of our meetings (we meet about monthly) if you have general questions. https://github.com/cncf/tag-contributor-strategy#meetings

**Comment by FeynmanZhou** [comment]
@geekygirldawn Thanks. Will TAG Contributor Strategy helps us handle this CoC issue?

**Comment by yizha1** [comment]
Thanks @TheFoxAtWork and @geekygirldawn, I created a PR to resolve this issue https://github.com/notaryproject/.github/pull/31
