### ISSUE TITLE
Sync the Notary maintainers to CNCF maintainer list 

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/.github#3]
CNCF uses the [maintainer list](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) as a reference to grant permissions to the project maintainers in some CNCF events, systems, or programs. However, there are only Notary Org owners listed on the CNCF [maintainer list](https://github.com/cncf/foundation/blob/main/project-maintainers.csv). To add other Notary owners to the CNCF maintainer list, we need to sync the Notary maintainers from [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) to the CNCF maintainer list. 

@toddysm @vaninrao10 @priteshbandi @yizha1 @iamsamirzon 
Do you have any concerns or suggestions about this proposal?

**Comment by toddysm** [comment]
LGTM

**Comment by yizha1** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by SteveLasker** [comment]
As mentioned earlier, the ask from CNCF (via @mattfarina) wasn't to surface every maintainer from each repo. Rather, the org maintainers as not every maintainer needs access to the CNCF tooling. We did discuss adding new org maintainers to provide more folks access.

**Comment by toddysm** [comment]
@SteveLasker @FeynmanZhou linked the [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) file for this (`.github`) repository that lists a subset of the list of maintainers on all the sub-projects. It does make sense to have the people who drive the governance to be the folks CNCF communicates with. It would be good to have this list of people also as Org maintainers but this is up to the current Org maintainers to decide on.

**Comment by SteveLasker** [comment]
- We have org maintainers - which we should expand
- We have sub-project maintainers, which have expanded - great.
- I'm hearing you define a new group, (> org maintainers, but < sub-project maintainers)

The org maintainers are the ones that should be working on the org governance, dealing with CNCF tools and such. Rather than define yet another group, I'd suggest we nominate additional org maintainers that can be active in the day-to-day operations.

**Comment by iamsamirzon** [comment]
I like the idea of expanding the list of org maintainers to include the people active in the day-to-day operations and setting the standards.

**Comment by vaninrao10** [comment]
LGTM -  expanding the list of org maintainers to include the people active in the day-to-day operations and setting the standards.

**Comment by toddysm** [comment]
@justincormack @SteveLasker @NiazFK Do we have your approval to expand the list of Org Maintainers with the folks listed in [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS)?

**Comment by justincormack** [comment]
SGTM

**Comment by SteveLasker** [comment]
Yes to adding org maintainers as that has been the goal for a while. The only caveat discussed was keeping the org maintainers balanced across orgs, avoiding any one company from becoming a majority. @NiazFK representing AWS, @justincormack  representing Docker and @toddysm representing Microsoft should nominate folks. We agreed to keep this at 3 per company.

**Comment by toddysm** [comment]
Based on the current list in the [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) the balance is: 4 AWS/3 MSFT/1 Docker/1 Independent. There is no simple majority for one company, and it will be hard to get super-majority without diverse votes. It would be good to get more folks from Docker to make it more balanced but I am OK with using the current list so we can unblock some work that is pending for a while already.

I will bring this to the next Notary meeting (3/20) for final agreement.

**Comment by toddysm** [comment]
I believe we have enough approvals on this issue to use the current MAINTAINERS list to sync as Org maintainers. We can always nominate new ones and amend the current list. What is the purpose of having a new one and starting over? We have been discussing this for a while already and it is blocking the work of the folks who are actively working on the project.

**Comment by toddysm** [comment]
As per the agreement from the Notary meeting today, the next steps we will take on this are the following:
- We will submit a PR to [maintainers.cncf.io](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) to add the folks listed in [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) as Notary Project maintainers
- We will create the GitHub Team for Org Maintainers as per #14 and include the folks listed in [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) and assign them as Org maintainers in GitHub
- Drop the emails of people who should have access to [maintainer-changes@cncf.io](mailto:maintainer-changes@cncf.io)
- Ping TAG Contributor Strategy on CNCF Slack

**Comment by FeynmanZhou** [comment]
We can close this issue as https://github.com/cncf/foundation/pull/524 has been merged.

**Comment by FeynmanZhou** [comment]
@toddysm I sent an email to [maintainer-changes@cncf.io](mailto:maintainer-changes@cncf.io) but it seems this email is invalid. I will ping Amye for this problem.

![image](https://user-images.githubusercontent.com/40452856/228000528-34803f75-eb5d-477d-9de9-39be44201c48.png)
