### ISSUE TITLE
Clean up stale branches in notation, notation-go, notaryproject

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/.github#33]
There are multiple stale branches in notation, notation-go, notaryproject repositories. We need to remove inactive branches in notation, notation-go, notaryproject.

**Comment by yizha1** [comment]
During [the community meeting on April 1](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#Notes),  we cleaned up stale branches in repository: `notation`, `notation-go` and `specifications` (original notaryproject).
