### ISSUE TITLE
Process for archiving repositories

### ISSUE THREAD

**Issue by toddysm** [notaryproject/.github#36]
I propose to have a documented process for archiving repositories. This should include details like:
- Under what conditions a repository can be archived?
- How is the decision to archive repository made?
- What happens with the repository before and after the archival?
- What documentation needs to be provided for users for the archived repository? (i.e. README.md updates etc.)

**Comment by iamsamirzon** [comment]
How do users of that current repo get notified that a repository has been archived? This is needed, so the current users can plan their migration

**Comment by FeynmanZhou** [comment]
> How do users of that current repo get notified that a repository has been archived? This is needed, so the current users can plan their migration

@iamsamirzon It's hard to inform all users of an open-source project. Maintainers can publish a blog post to share the archiviation information publicly.

**Comment by FeynmanZhou** [comment]
@toddysm I raised a PR to clarify the repository lifecycle and the process of archiving a repository. PTAL #37
