### ISSUE TITLE
Proposal for renaming notaryproject\notaryproject to notaryproject\specifications

### ISSUE THREAD

**Issue by toddysm** [notaryproject/.github#38]
As part of the discussions we are having about cleaning up the branding (#32 and #35) there is a proposal to archive the `notaryproject` repository as it is confusing and replace it with a new repository. This issue is intended to describe the proposal for the new repository, its purpose and structure. 

The proposal is to create a new repository with the name `specifications` that will contain specifications shared across "subprojects" under Notary Project as well as used by other OSS projects and/or vendor tools that want to interoperate with Notary Project tooling. Here the details:
- Repository name: `specifications`
- Repository purpose: Cross tooling and interoperability specifications
- Structure:
    - `specifications` repository
        - `oci-signature-specification` folder
          Those specifications are OCI specific and describe how the Notary Project Signing Scheme is applied to signatures stored in OCI registries. The folder contains the following documents:
            - [Signature Specification](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-specification.md) referred to as _"Notary Project OCI Signature Specification"_ or just _"OCI Signature Specification"_ if the Notary Project reference is implied.
            - [Signing and Verification Workflow](https://github.com/notaryproject/notaryproject/blob/main/specs/signing-and-verification-workflow.md) referred to as _"Notary Project OCI Signing and Verification Workflow"_ or just _"OCI Signing and Verification Workflow"_ if the Notary Project reference is implied.
            - [Signing Envelope COSE](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-envelope-cose.md) referred to as _"Notary Project OCI COSE Envelope"_ or just _"OCI COSE Envelope"_ if the Notary Project reference is implied. Ideally, we would like to have COSE envelope spec that is not specific to OCI.
            - [Signing Envelope JWS](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-envelope-jws.md) referred to as _"Notary Project OCI JWS Envelope"_ or just _"OCI JWS Envelope"_ if the Notary Project reference is implied. Ideally, we would like to have JWS envelope spec that is not specific to OCI.
        - `signing-scheme` folder
          This specification is not specific to any storage and describes the supported signing schemes. Ideally any tool that supports those schemes should be able to produce signatures that are understood by Notary Project tools. Ideally, we would like to have non-OCI specific envelope specifications in this folder also. This folder contains the following documents:
            - [Signing Scheme](https://github.com/notaryproject/notaryproject/blob/main/specs/signing-scheme.md) referred to as _"Notary Project Signing Scheme"_ or just _"Signing Scheme"_ if the Notary Project reference is implied.

In the future, this repository may contain specifications about identities, attestations, counter receipts, etc. depending on how the Notary Project evolves.

**Comment by sajayantony** [comment]
Adding @gokarnm in this conversation since the comment - https://github.com/notaryproject/notary/pull/1685#issuecomment-1610321068 is related to this proposal.

**Comment by FeynmanZhou** [comment]
I think the term "OCI" has been implied in the folder name so it's not necessary to replicate "OCI" in each individual file name.

Considering the user's search habits and SEO, I would suggest including "Notary Project" in each individual file name (URL) and also the document title. Using a too simple and generic title is not beneficial for SEO. My proposed structure are as follows

- Folder: `oci-signature-specification`
   - File:  [Signature Specification](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-specification.md) --> "Notary Project Signature Specification"
   - File: [Signing and Verification Workflow](https://github.com/notaryproject/notaryproject/blob/main/specs/signing-and-verification-workflow.md) --> "Notary Project Signing and Verification Workflow" 
   - File: [Signing Envelope COSE](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-envelope-cose.md) --> "Notary Project COSE Envelope"
   - File: [Signing Envelope JWS](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-envelope-jws.md) --> "Notary Project JWS Envelope"
- Folder: `Notary Project Signing Scheme`

**Comment by toddysm** [comment]
@FeynmanZhou those specifications may be referred from specifications, blog posts, articles and other documents that are not in that folder and without the context of the folder name. That is why it is important to define a clear name for them to avoid ambuiguity.

**Comment by iamsamirzon** [comment]
@toddysm   - Is there a proposal for the other two specifications currently present in the https://github.com/notaryproject/notaryproject/tree/main/specs - The [plugin-extensibility.md](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md) and [trust-store-trust-policy.md](https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md) ?

Also, what about the other sub folders in the [notaryproject repo](https://github.com/notaryproject/notaryproject)  - Security, Requirements, media

**Comment by toddysm** [comment]
@iamsamirzon thanks for asking.
- plugin and trust store are very specific to Notation, so those should be specs under Notation IMHO
- regarding the security audits, we should have those in the `.github` repo if they are across subprojects or in the specific repos if they are specific to a subproject

**Comment by sajayantony** [comment]
I believe this issues needs to be retitled as renmae `notaryproject\notaryproject` to `notaryproject\specficiation` 
Just to confirm is it specification or specfications? the repository could be specification and not plural similar to image-spec/distribution-spec tuf spec etc.

**Comment by yizha1** [comment]
We may need to separate the signature storage from signature specification and write a new specification for signature storage, since the signature can be stored in OCI compliant registries or in a filesystem as a file, see https://github.com/notaryproject/notation/issues/741

**Comment by yizha1** [comment]
As one work item from the approved proposal https://github.com/notaryproject/.github/issues/35#issuecomment-1642938826 and alignment in [community meeting on Jul 24 PDT](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Meeting-Notes), this proposal requires a two-thirds supermajority of the maintainer votes, please reply `LGTM` to this proposal. As the one writing this proposal, my vote is `LGTM`.

@SteveLasker @justincormack @NiazFK @gokarnm @toddysm @FeynmanZhou @vaninrao10 @priteshbandi @iamsamirzon

**Comment by SteveLasker** [comment]
> Just a question: Based on proposal https://github.com/notaryproject/.github/issues/35 , folder "requirements" will not be maintained any more.

I'd agree with [@TheFoxAtWork for this comment](https://github.com/notaryproject/.github/issues/35#issuecomment-1598859193): 
> Requirements may be captured as GH issues however it may also be prudent to record high level 'requirements' or design principles as Scoping Goals/ Guide that the project and its community members may continuously refer back to when determining overall features, design criteria, and the acceptable characteristics for PRs.

Keeping the requirements and scenarios as a single doc, provides context to the purpose of the project and it's goals. Which should continue to evolve. Converting these to issues or archiving would lose that context in a meaningful way.

**Comment by yizha1** [comment]
Thanks @SteveLasker . 

I will create a separate issue for addressing the folder structure. This issue will be used for Proposal for renaming `notaryproject\notaryproject` to `notaryproject\specifications`

**Comment by yizha1** [comment]
@SteveLasker @justincormack @NiazFK @gokarnm @toddysm @FeynmanZhou @vaninrao10 @priteshbandi @iamsamirzon 

Please reply `LGTM` to if you agree on renaming `notaryproject\notaryproject` to `notaryproject\specifications`
As the one writing this vote, my response is `LGTM`.


Regarding to folder structure discussion, please go to this issue https://github.com/notaryproject/.github/issues/48

**Comment by toddysm** [comment]
I created the proposal, so my +1 should be implicit 😀

**Comment by yizha1** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM

**Comment by gokarnm** [comment]
LGTM, except for [Trust Store and Trust Policy](https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md) should be part of the Notary Project specifications, it has the core verification logic that is references from the OCI specific steps in [Signing and Verification Workflow](https://github.com/notaryproject/notaryproject/blob/main/specs/signing-and-verification-workflow.md).

**Comment by priteshbandi** [comment]
LGTM for renaming, we will have separate issue for restructure of pkg.

**Comment by justincormack** [comment]
LGTM

**Comment by yizha1** [comment]
The renaming and purpose of repository were updated, see https://github.com/notaryproject/specifications

@toddysm Maybe we can close this issue and refer to https://github.com/notaryproject/.github/issues/48 for folder structure and content discussion.

**Comment by yizha1** [comment]
Close as the renaming was completed. Please go to https://github.com/notaryproject/.github/issues/48 for folder structure and content discussion.
