### ISSUE TITLE
Manage pinned repositories in the GitHub org page

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/.github#41]
From [Pinning items to your profile - GitHub Docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile), it states that Pinned section showcases the repositories that best represent your work. Org-level maintainers have the responsibility and access to manage the pinned section based on the sub-project activity.

For example, it's obvious that this repo [notaryproject/tuf](https://github.com/notaryproject/tuf) is inactive and might be archived eventually. We may need to unpin [notaryproject/tuf](https://github.com/notaryproject/tuf) and regularly pin some active repositories in that section. If the [notaryproject](https://github.com/notaryproject/notaryproject) is archived in the near future as mentioned in #35 , it should also be unpinned. 

Hi Team @notaryproject/notaryproject-org-maintainers , could you pls help handle it?

![image](https://github.com/notaryproject/.github/assets/40452856/c88bc8d0-a159-4f01-8181-e8d0d9c028a0)

**Comment by yizha1** [comment]
Closed as completed
