### ISSUE TITLE
Proposal for renaming notaryproject/notary repository to notaryproject/notary-tuf 

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#44]
As discussed in issue #35 for bringing clarity to the Notary Project branding, one of the proposals is to rename `notaryproject/notary` repository to `notaryproject/notary-tuf`. The reason is the repository `notaryproject/notary` contains the source code for the server and the client of the TUF-based implementation under Notary Project organization. Adding `tuf` in the repository name makes it clear for the broad community and contributors that this repository contains only TUF-based implementation.

**Comment by yizha1** [comment]
As one work item from the approved prospoal https://github.com/notaryproject/.github/issues/35#issuecomment-1642938826 and alignment in [community meeting on Jul 24 PDT](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Meeting-Notes), this proposal requires a two-thirds supermajority of the maintainer votes, please reply `LGTM` to this proposal. As the one writing this proposal, my vote is `LGTM`

@SteveLasker @justincormack @NiazFK @gokarnm @toddysm @FeynmanZhou @vaninrao10 @priteshbandi @iamsamirzon

**Comment by toddysm** [comment]
LGTM

**Comment by yizha1** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM

**Comment by SteveLasker** [comment]
Have you had any engagement from the [notary maintainers or contributors](https://github.com/notaryproject/notary/blob/master/CONTRIBUTORS)? If they don't respond, with an effort to contact them, and enough time for them to respond, I'm okay with this change.

**Comment by justincormack** [comment]
I don't think this makes sense. This project has had this name for a long time, and in future other repositories here may use TUF. The aim of giving other projects new names was to avoid any confusion, so this seems unnecessary.

**Comment by HuKeping** [comment]
I would prefer keep the name as `notary`

**Comment by toddysm** [comment]
As per the above comments and discussion in the [Notary Project community meeting on Aug 3rd 2023](https://www.youtube.com/watch?v=FIEkkduYCDA) we should keep the name as is. Closing the issue as resolved.
