### ISSUE TITLE
Nominate Toddy Mladenov (@toddysm) as a Notary Project Org maintainer

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#55]
At the [Notary Project community meeting](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Notes) held on December 4, 2023, the community discussed and agreed on nominating new [Notary Project Org maintainers](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers) from subproject maintainers according to the [governance guide](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers).

I would like to nominate Toddy Mladenov (@toddysm) as a Notary Project Org maintainer. Toddy has been a Notary Project subproject maintainer for subprojects: [specification](https://github.com/notaryproject/specifications/blob/main/MAINTAINERS), [notaryproject.dev](https://github.com/notaryproject/notaryproject.dev/blob/main/MAINTAINERS), [.github](https://github.com/notaryproject/.github/blob/main/MAINTAINERS), [roadmap](https://github.com/notaryproject/roadmap/blob/main/MAINTAINERS), [meeting-notes](https://github.com/notaryproject/meeting-notes/blob/main/MAINTAINERS). He has made significant contributions to the Notary Project since joining the community. 

From routine work perspective, based on the maintainer activities status in the last 12 months, Toddy Mladenov (@toddysm) has demonstrated a high meeting participation rate and has contributed significantly to various areas, including creating PRs to solve problems directly, creating issues for bug fixes and enhancement, and actively reviewing PRs and providing comments for issues. The following table shows his contributions to the Notary Project sub-projects:
 | Name (GitHub ID) | PR | Issue | PR comments | Issue comments | Meetings |
| -------------------- | --- | ----- | --------------- | ------------------ | ---------- |
 | Toddy Mladenov (@toddysm)     | 12  | 53    | 186         | 120            | 61/78    |

Toddy has also demonstrated his leadership in governance-related work, particularly during the time of clarity of the Notary Project brand. He made a very insightful [proposal](https://github.com/notaryproject/.github/issues/35) and led the whole community to deliver the results, receiving [positive feedback from CNCF annual review](https://github.com/cncf/toc/pull/1187#pullrequestreview-1690530333). The following table shows his contribution to governance work items under the `.github` repo in the last 12 months:

| Name (GitHub ID) | PR | Issue | PR comments | Issue comments | 
 | -------------------- | --- | ----- | --------------- | ------------------ | 
Toddy Mladenov (@toddysm)     | 3  | 6    | 42         | 41            |

Last but not least, in the last 12 months, Toddy Mladenov (@toddysm) has participated in several KubeCon events as a speaker to introduce the solution that Notary Project offers together with partners from other communities. He has also participated in project booths to answer questions, demos, and make connections in KubeCon. Recently, Toddy did an excellent enlightening podcast with another maintainer, @gokarnm, which greatly improved the visibility of Notary Project and helped a broad community to know what Notary Project is. The following table shows more information in the last 12 months.

| Name (GitHub ID)                | Activities |
| ------------------------------- | ---------- |
| Toddy Mladenov (@toddysm)       | [KubeCon EU 2023](https://kccnceu2023.sched.com/event/1HyUS/securing-the-container-supply-chain-with-notary-justin-cormack-docker-toddy-mladenov-microsoft), [KubeCon NA 2023](https://kccncna2023.sched.com/event/1R2sK/improving-the-security-of-software-supply-chains-with-notary-project-toddy-mladenov-microsoft-milind-gokarn-amazon), [Notation Security audit 2023](https://github.com/notaryproject/specifications/blob/main/security/reports/audit/ADA-notation-security-audit-23.pdf), [Enlightening Podcast](https://notaryproject.dev/blog/2023/notary-enlightning-podcast/) |

I believe that Toddy Mladenov (@toddysm)'s experience and expertise will be an asset to the Notary Project, and I am confident that he will continue to make valuable contributions to the community.

> The data shown in above tables is copied from source https://github.com/notaryproject/.github/issues/54

Please comment "+1" to vote for Toddy Mladenov (@toddysm), according to the governance guide and agreement on community meeting, we need two votes out of three from current org maintainers. 
Tag Org maintainers: @NiazFK @justincormack @SteveLasker 

/cc other maintainers: @cipherboy @OliverShang @FeynmanZhou @HuKeping @JeyJeyGao @duffney @gokarnm @mnm678 @priteshbandi @Two-Hearts @rgnote @iamsamirzon @toddysm @shizhMSFT @vaninrao10 @yizha1 @zr-msft

**Comment by Two-Hearts** [comment]
+1

**Comment by SteveLasker** [comment]
+1 support

**Comment by justincormack** [comment]
+1

**Comment by priteshbandi** [comment]
+1

**Comment by NiazFK** [comment]
+1

**Comment by vaninrao10** [comment]
+1 as per discussion in the meeting.

**Comment by toddysm** [comment]
As per discussion in this morning's community discussion and based on the votes above we decided to move forward with adding my name as well as #56 and #57 to the Org maintainers. I will go ahead and create the necessary PRs to update the relevant MAINTAINERS and CODEOWNERS files
