### ISSUE TITLE
Nominate Shiwei Zhang (@shizhMSFT) as a Notary Project Org maintainer

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#56]
At the [Notary Project community meeting](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Notes) held on December 4, 2023, the community discussed and agreed on nominating new [Notary Project Org maintainers](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers) from subproject maintainers according to the [governance guide](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers).

I would like to nominate Shiwei Zhang (@shizhMSFT) as a Notary Project Org maintainer. Shiwei Zhang (@shizhMSFT) has been a Notary Project subproject maintainer for subprojects: [specifications](https://github.com/notaryproject/specifications/blob/main/MAINTAINERS), [notation](https://github.com/notaryproject/notation/blob/main/MAINTAINERS), [notation-go](https://github.com/notaryproject/notation-go/blob/main/MAINTAINERS), [notation-core-go](https://github.com/notaryproject/notation-core-go/blob/main/MAINTAINERS), [notation-action](https://github.com/notaryproject/notation-action/blob/main/MAINTAINERS) and [notation-plugin-framework-go](https://github.com/notaryproject/notation-plugin-framework-go/blob/main/MAINTAINERS). He has made significant and unique contributions to the Notary Project since joining the community. 

From routine work perspective, Shiwei Zhang (@shizhMSFT) has demonstrated a high meeting participation rate considering the time zone and has contributed significantly to quality control by reviewing PRs and providing comments on issues. The following table shows his contributions to the Notary Project sub-projects in the last 12 months. He has made amazing 681 PR comments, almost 2 comments on PR per day.
 | Name (GitHub ID) | PR | Issue | PR comments | Issue comments | Meetings |
| -------------------- | --- | ----- | --------------- | ------------------ | ---------- |
| Shiwei Zhang (@shizhMSFT)     | 8   | 20    | 681         | 168            | 40/78    |

Not only the number of comments, if you take a deeper look at the comments that Shiwei Zhang (@shizhMSFT) made, those are very insightful and deep thought comments, see an example https://github.com/notaryproject/notation/pull/601#discussion_r1150810148. For maintainers and contributors, I believe you all have the feeling that if your PRs are reviewed and approved by Shiwei Zhang (@shizhMSFT), it means high quality.

Shiwei Zhang (@shizhMSFT) is a security expert. He led the design and implementation of the [Notary Project COSE signature](https://github.com/notaryproject/specifications/blob/v1.0.0/specs/signature-envelope-cose.md) in `notation-core-go` library and is the main contributor to the `go-cose` library, which is used by the `notation-core-go` library. He has also demonstrated his expertise in the recent security audit and has received credits for several security advisories. Not to mention the latest [notation threat model](https://github.com/notaryproject/specifications/blob/v1.0.0/threatmodels/notation-threatmodel.md) was created with his guidance.

Last but not least, Shiwei Zhang (@shizhMSFT) participated in KubeCon China (Due to the pandemic, this conference has not been held for several years) and promote Notary Project solutions. He answered questions, did demos for folks who were interested in the Notary Project at the project booth. The following table shows more information about his activities in the last 12 months:

| Name (GitHub ID)                | Activities |
| ------------------------------- | ---------- |
| Shiwei Zhang (@shizhMSFT)       | KubeCon China 2023 (project booth), [Notation Security audit 2023](https://github.com/notaryproject/specifications/blob/main/security/reports/audit/ADA-notation-security-audit-23.pdf) |

I believe that Shiwei Zhang (@shizhMSFT)'s experience and security expertise will be an asset to the Notary Project, and I am confident that he will continue to make valuable contributions to the community.

> The data shown in above tables is copied from source https://github.com/notaryproject/.github/issues/54

Please comment "+1" to vote for Shiwei Zhang (@shizhMSFT), according to the governance guide and agreement on community meeting, we need two votes out of three from current org maintainers. 
Tag Org maintainers: @NiazFK @justincormack @SteveLasker 

/cc other maintainers: @cipherboy @OliverShang @FeynmanZhou @HuKeping @JeyJeyGao @duffney @gokarnm @mnm678 @priteshbandi @Two-Hearts @rgnote @iamsamirzon @toddysm @shizhMSFT @vaninrao10 @yizha1 @zr-msft

**Comment by Two-Hearts** [comment]
+1

**Comment by justincormack** [comment]
+1

**Comment by HuKeping** [comment]
+1




________________________________

Hu Keping
***@***.***
(From WeLink)

发件人：Feynman Zhou ***@***.***>
收件人：notaryproject/.github ***@***.***>
抄 送：hukeping ***@***.***>;Mention ***@***.***>
时 间：2023-12-08 17:10:29
主 题：Re: [notaryproject/.github] Nominate Shiwei Zhang ***@***.***) as a Notary Project Org maintainer (Issue #56)


+1

―

**Comment by SteveLasker** [comment]
+1

**Comment by priteshbandi** [comment]
+1

**Comment by NiazFK** [comment]
+1

**Comment by vaninrao10** [comment]
+1 as per the discussion in the meeting.

**Comment by toddysm** [comment]
As per discussion in this morning's community discussion and based on the votes for @shizhMSFT we decided to move forward with adding him to the Org maintainers. I will go ahead and create the necessary PRs to update the relevant MAINTAINERS and CODEOWNERS files
