### ISSUE TITLE
Nominate Pritesh Bandi (@priteshbandi) as a Notary Project Org maintainer

### ISSUE THREAD

**Issue by gokarnm** [notaryproject/.github#57]
As per [Notary Project community meeting](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Notes) held on December 4, 2023, the community discussed and agreed on nominating new [Notary Project Org maintainers](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers) from subproject maintainers according to the [governance guide](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers).

I would like to nominate Pritesh Bandi (@priteshbandi) as a Notary Project Org maintainer. He has been a Notary Project subproject maintainer for various sub-projects such as [specifications](https://github.com/notaryproject/specifications/blob/main/MAINTAINERS), [notation](https://github.com/notaryproject/notation/blob/main/MAINTAINERS), [notation-go](https://github.com/notaryproject/notation-go/blob/main/MAINTAINERS), [notation-core-go](https://github.com/notaryproject/notation-core-go/blob/main/MAINTAINERS), [notaryproject.dev](https://github.com/notaryproject/notaryproject.dev/blob/main/MAINTAINERS) and [notation-plugin-framework-go](https://github.com/notaryproject/notation-plugin-framework-go/blob/main/MAINTAINERS) and has made significant contributions to the Notary Project since joining the community. 

In terms of regular work activities, he has been regular in community meetings and has made substantial contributions to quality control. This was achieved through the review of PRs (Pull Requests) and offering comments on issues. The following table shows his contributions to the Notary Project sub-projects in the last 12 months
 | Name (GitHub ID) | PR | Issue | PR comments | Issue comments | Meetings |
| -------------------- | --- | ----- | --------------- | ------------------ | ---------- |
| Pritesh Bandi (@priteshbandi )     | 36   | 27    | 438         | 176            | 52/78    |

_source https://github.com/notaryproject/.github/issues/54_

He played a crucial role in creating specifications for the Notary Project. These specifications define processes for generating and verifying signatures, trust stores and policies and signing/verification of arbitrary data. Also, his impactful feedback on specifications and their implementation is evident through his pull requests, pull request comments and issue comments.

I believe that Pritesh Bandi (@priteshbandi)'s experience and expertise will be an asset to the Notary Project, and I am confident that he will continue to make valuable contributions to the community. Please comment "+1" to vote for Pritesh Bandi (@priteshbandi ), according to the governance guide and agreement on community meeting, we need two votes out of three from current org maintainers. 

Tagging Org maintainers: @NiazFK @justincormack @SteveLasker 
CC other maintainers: @cipherboy @OliverShang @FeynmanZhou @HuKeping @JeyJeyGao @duffney @gokarnm @mnm678 @priteshbandi @Two-Hearts @rgnote @iamsamirzon @toddysm @shizhMSFT @vaninrao10 @yizha1 @zr-msft

**Comment by shizhMSFT** [comment]
+1

**Comment by FeynmanZhou** [comment]
+1 Support. @priteshbandi has been actively contributing to multiple sub-projects in 2023.

**Comment by toddysm** [comment]
+1 support.

**Comment by yizha1** [comment]
+1 support

**Comment by SteveLasker** [comment]
+1 support

**Comment by Two-Hearts** [comment]
+1

**Comment by toddysm** [comment]
+1 support

**Comment by NiazFK** [comment]
+1

**Comment by toddysm** [comment]
As per discussion in this morning's community discussion and based on the votes for @priteshbandi we decided to move forward with adding him to the Org maintainers. I will go ahead and create the necessary PRs to update the relevant MAINTAINERS and CODEOWNERS files
