### ISSUE TITLE
Vote: a new repository for implementation of a subset of pkcs7/CMS (RFC5652)

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#59]
I would like to propose the creation of a new repository for implementation of a subset of pkcs7/CMS (Cryptographic Message Syntax) as specified in ([RFC5652](https://datatracker.ietf.org/doc/html/rfc5652)). This repo will be used by `timestamp` repo, which is proposed in https://github.com/notaryproject/.github/issues/58. 

Here are the details:

Repository name, two options:

- Option-1: `pkcs7`
- Option-2: `cms`

Description: 

This repository contains an implementation of a subset of pkcs7/CMS (Cryptographic Message Syntax) as specified in [RFC5652](https://datatracker.ietf.org/doc/html/rfc5652).

@notaryproject/notaryproject-governance-maintainers If you agree with above proposal, please comment `LGTM` or `+1` and the repository name (`pkcs7` or `cms`) that you preferred.

**Comment by priteshbandi** [comment]
Do we really need separate repo for pkcs7? Can this code go in timestamp repo ?

**Comment by yizha1** [comment]
> Do we really need separate repo for pkcs7? Can this code go in timestamp repo ?

This repo allows users to use or contribute to pkcs7 separately. Some users may not need timestamp functionality.

**Comment by priteshbandi** [comment]
The 'timestamp' repository should not include any additional third-party dependencies beyond the 'pkcs7' repository. This setup ensures that users wishing to utilize the 'pkcs7' module need not be overly concerned about taking a dependency on the 'timestamp' repository.

Initially, we can consolidate the pkcs7 related code within the 'timestamp' repository. If necessary, we can subsequently separate the pkcs7-related module and place it in its dedicated repository. This process should be relatively straightforward, primarily involving updates to the 'timestamp' package only.

**Comment by yizha1** [comment]
Thanks @priteshbandi. I will close this vote, and update vote https://github.com/notaryproject/.github/issues/58 to include the pkcs7/cms module.
