### ISSUE TITLE
Refactor contributing guide for Notary project

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/.github#6]
The notary project has a [contributing guide](https://github.com/notaryproject/.github/blob/main/CONTRIBUTING.md) migrated from the [Notary repo](https://github.com/notaryproject/notary/blob/master/CONTRIBUTING.md). It's currently in a rough version and most of the content is outdated. 

To help new folks understand the contributing process and development workflow of the Notary project, we should consider providing a general contributing guide for the whole Notary project, including code (Notation CLI and go library repositories) and non-code (website, spec, governance) contributions.

**Comment by yizha1** [comment]
The first version [contributing guide](https://github.com/notaryproject/.github/blob/main/CONTRIBUTING.md) was created with this PR merged https://github.com/notaryproject/.github/pull/17
The next step is to amend the guide based on the needs.

**Comment by yizha1** [comment]
@FeynmanZhou we can close this issue to avoid long lead time, since contributing guide has been migrated to this repo. We can create new issues when there is a need to amend the guide in the future.

**Comment by yizha1** [comment]
This issue is for updating governance related documents. Clear milestone to avoid mixing with Notation releases.
