### ISSUE TITLE
Stepping Down as Org Maintainer

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/.github#66]
With the Notary Project making great progress and my focus on other IETF SCITT work, it's time I step down as an Org Maintainer.

It's been great to see the project evolve, and the new maintainers (@toddysm, @priteshbandi, @shizhMSFT) taking on their roles.

**Comment by toddysm** [comment]
@SteveLasker I would like to thank you for your work on Notary Project and for helping bring it to its current state. I wish you good luck with your new endeavors.

**Comment by shizhMSFT** [comment]
@SteveLasker Thank you for your contributions to the Notary Project. I appreciate your hard work and dedication in helping the project evolve. I wish you all the best in your future endeavors.

**Comment by priteshbandi** [comment]
@SteveLasker, I would like to thank you for your contributions to the Notary Project. Your dedication and hard work in advancing the project are truly appreciated. Wishing you the very best in your future endeavors.

**Comment by yizha1** [comment]
@SteveLasker  I wanted to take a moment to thank you for your contributions to the Notary Project, and your support when I joined the community. I wish you all the best in your future endeavors.

**Comment by FeynmanZhou** [comment]
@SteveLasker  I am also grateful that you made a lot of contributions the Notary Project and reviewed a lot of my work when I joined the community. I wish you all the best and hope we could continue to collaborate in the open-source community.

**Comment by vaninrao10** [comment]
@SteveLasker, I would like to thank you for your contributions to the Notary Project. Your subject matter expertise and deep dive discussions during design discussions truly had a major impact for the project. Wishing you all the very best and good luck for your future endeavors.

**Comment by NiazFK** [comment]
@SteveLasker thank you for all your contributions to the Notary Project and sharing so many valuable insights from the industry. I wish you all the best with the IETF SCTT work and other future endeavors.

**Comment by yizha1** [comment]
Closed this issue as completed. MAINTAINERS and CODEOWNERS were updated in each repository.
