### ISSUE TITLE
Nominate Yi Zha as a Notary Project Org maintainer

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/.github#67]
As per [Notary Project community meeting](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Notes) held on December 4, 2023, the community discussed and agreed on nominating new [Notary Project Org maintainers](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers) from sub-project maintainers according to the [governance guide](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers). This month, we also aligned that keep the total number of [org maintainers as 6](https://github.com/notaryproject/.github/issues/60).

I would like to nominate Yi Zha (@yizha1) as a Notary Project Org maintainer. He has been a Notary Project sub-project maintainer for various important sub-projects such as [specifications](https://github.com/notaryproject/specifications/blob/main/MAINTAINERS), [notation](https://github.com/notaryproject/.github/blob/main/MAINTAINERS), [notaryproject.dev](https://github.com/notaryproject/notaryproject.dev/blob/main/MAINTAINERS) and has made significant contributions to the Notary Project since joining the community. 

In terms of routine work activities in the community, he has been a moderator for the community meetings more than 1 year and has made substantial contributions to the whole organization. This was achieved through the review of PRs (Pull Requests) and offering comments on issues. The following table shows his contributions to the Notary Project sub-projects in the last 12 months

| Sub-projects                                                                                                                                             | Name (GitHub ID)              | PR | Issue  | PR comments | Issue comments |
| -------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------- | --- | ----- | ----------- | -------------- |
| `.github`, `roadmap`, `meeting-notes`, `specification`, `notaryproject.dev`                                                                              | Yi Zha (@yizha1)              | 69  | 110   | 506         | 493            | 

The data shown in above tables is copied from source https://github.com/notaryproject/.github/issues/54

As a governance maintainer, he helped the community to build up governance process and refactored the [contributing guide](https://github.com/notaryproject/.github/pull/25). He also contributed to the [Notation Security audit 2023](https://github.com/notaryproject/specifications/blob/main/security/reports/audit/ADA-notation-security-audit-23.pdf) and finished the latest [Notation threat model](https://github.com/notaryproject/specifications/blob/v1.0.0/threatmodels/notation-threatmodel.md) with quality.

In terms of community advocacy, he had a talk at [KubeCon China 2023](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/program/schedule/) and shared the supply chain security best practices in the industry.

I believe that Yi Zha (@yizha1)'s experience and expertise will be an asset to the Notary Project, and I am confident that he will continue to make valuable contributions to the community. Please comment "+1" to vote for him if you agree with this nomination. Thanks!

Tagging Org maintainers: @notaryproject/notaryproject-org-maintainers 

CC other sub-project maintainers: @cipherboy @OliverShang @HuKeping @JeyJeyGao @duffney @gokarnm @mnm678 @Two-Hearts @rgnote @iamsamirzon @toddysm @shizhMSFT @vaninrao10

**Comment by shizhMSFT** [comment]
+1

**Comment by toddysm** [comment]
+1

**Comment by OliverShang** [comment]
+1

**Comment by SteveLasker** [comment]
+1

**Comment by JeyJeyGao** [comment]
+1

**Comment by Two-Hearts** [comment]
+1

**Comment by whalelines** [comment]
+1

**Comment by priteshbandi** [comment]
+1

**Comment by gokarnm** [comment]
+1

**Comment by yizha1** [comment]
Per [the community meeting on April 1](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#Notes),  as Steve Lasker and Justin Cormark are moved to emeritus status. As a result, three out of the four org maintainers have voted in favor of nominating Yi as a Notary Project Org maintainer. @toddysm will create PRs to update org maintainers in each repository.

**Comment by yizha1** [comment]
Closed this issue as nomination was completed. MAINTAINERS and CODEOWNERS were updated in each repository.
