### ISSUE TITLE
Move Justin Cormack (@justincormack) to emeritus

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#68]
Proposal to move Justin Cormack (@justincormack) to emeritus due to inactivity as per [issue #54](https://github.com/notaryproject/.github/issues/54) and the Notary Project [governance](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md). It will be an honor to have Justin as a maintainer in the future if his contributions meet the maintainer guidelines described in the project governance. I appreciate Justin’s leadership and contributions to the Notary Project over the years. Please comment "+1" if you agree with this proposal. @notaryproject/notaryproject-org-maintainers

**Comment by justincormack** [comment]
SGTM!

**Comment by toddysm** [comment]
I would like to thank @justincormack for all his contributions to the project over the years and for helping bring it to its current state. Looking forward to continuing working with Docker in the community.

**Comment by yizha1** [comment]
Closed this issue as completed. MAINTAINERS and CODEOWNERS were updated in each repository.
