### ISSUE TITLE
Nominate Vani Rao (@vaninrao10) as a Notary Project Org maintainer

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/.github#69]
At the [Notary Project community meeting](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#Notes) held on January 22, 2024, the community discussed and agreed on nominating new [Notary Project Org maintainers](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers) from subproject maintainers according to the [governance guide](https://github.com/notaryproject/.github/blob/main/GOVERNANCE.md#notary-project-org-maintainers).
I would like to nominate Vani Rao ([@vaninrao10](https://github.com/vaninrao10)) as a Notary Project Org maintainer. Vani has been a Notary Project subproject maintainer for subprojects: [specification](https://github.com/notaryproject/specifications/blob/main/MAINTAINERS), [notaryproject.dev](http://notaryproject.dev/), [.github](https://github.com/notaryproject/.github/blob/main/MAINTAINERS), [roadmap](https://github.com/notaryproject/roadmap/blob/main/MAINTAINERS), [meeting-notes](https://github.com/notaryproject/meeting-notes/blob/main/MAINTAINERS). She has made good contributions to the Notary Project since joining the community.
From routine work perspective, based on the maintainer activities status in the last 18 months, Vani Rao ([@vaninrao10](https://github.com/vaninrao10)) has demonstrated a high meeting participation rate and has contributed significantly to various areas, including creating PRs to solve problems directly, creating issues for bugs and enhancement, and actively reviewing PRs and providing comments for issues. The following table shows her contributions to the Notary Project sub-projects:
 | Name (GitHub ID) | PR | Issue | PR comments | Issue comments | Meetings |
| -------------------- | --- | ----- | --------------- | ------------------ | ---------- |
 |   Vani Rao ([@vaninrao10](https://github.com/vaninrao10)) | 44 | 83 | 44 | 83 | 34 |
 
Vani has showcased her leadership skills in governance-related tasks, notably during the period of defining the Notary Project brand. I am confident that Vani Rao's ([@vaninrao10](https://github.com/vaninrao10)) experience and expertise will greatly benefit the Notary Project, and I trust that she will continue to provide valuable contributions to the community.

Please comment "+1" to vote for Vani Rao ([@vaninrao10](https://github.com/vaninrao10)), according to the governance guide and agreement on community meeting, we need two votes out of three from current org maintainers.

**Comment by priteshbandi** [comment]
+1

**Comment by toddysm** [comment]
+1

**Comment by whalelines** [comment]
+1

**Comment by yizha1** [comment]
+1

**Comment by shizhMSFT** [comment]
+1

**Comment by FeynmanZhou** [comment]
+1 support

**Comment by gokarnm** [comment]
+1

**Comment by yizha1** [comment]
Per [the community meeting on April 1](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#Notes),  as Steve Lasker and Justin Cormark are moved to emeritus status. As a result, three out of the four org maintainers have voted in favor of nominating Vani as a Notary Project Org maintainer. @toddysm will create PRs to update org maintainers in each repository.

**Comment by yizha1** [comment]
Closed this issue as nomination was completed. MAINTAINERS and CODEOWNERS were updated in each repository.
