### ISSUE TITLE
Create Notary project GOVERNANCE.md

### ISSUE THREAD

**Issue by yizha1** [notaryproject/.github#7]
The Notary governance document `GOVERNANCE.md` should cover the following aspects:

- The Notary project intro
- Maintainers Structure
- Org Maintainers responsibility
- Process of stepping down, process of onboarding new org maintainers 
- Subproject Maintainers responsibility
- Process of stepping down, process of onboarding new Subproject maintainers
- Maintainers health state and regular review process for maintainers
- Decision Making at the Notary org level
- Code of Conduct
- DCO and Licenses

**Comment by yizha1** [comment]
There is an existing governance guide under sub-project `Notary`, see https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md. 

- option1: Move existing governance.md from `Notary` repo to `.github` repo and update it if needed.
- option2: create a new one under `.github` and keep the existing one under `Notary` repo as it is.

Any other options? Looking for comments from the maintainers and community.

**Comment by FeynmanZhou** [comment]
I vote for 1. The existing [Notary governance doc](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md) is reusable and most of the content is still applicable to our community. We could migrate it to this repo and iterate it.

Instead, it will confuse people if an organization has two different governance guidelines.

**Comment by priteshbandi** [comment]
+1 for option1

**Comment by vaninrao10** [comment]
+1 for option 1, but if we plan to move away from Notary and keep Notation we need to have appropriate plan in place.

**Comment by toddysm** [comment]
We agreed a while back that we will move the governance documents from the `notary` repo to this one. Let's do that first and we can amend those after that if needed. We should move not only the GOVERNANCE but also the other governance docs like 
https://github.com/notaryproject/notary/blob/master/CODE_OF_CONDUCT.md 
https://github.com/notaryproject/notary/blob/master/CONTRIBUTING.md
https://github.com/notaryproject/notary/blob/master/PROJECTS

+1 on Option #1

**Comment by yizha1** [comment]
> +1 for option 1, but if we plan to move away from Notary and keep Notation we need to have appropriate plan in place.

@vaninrao10 could you explain what do you mean "keep Notation"? Both `notary` and `notation` are sub-projects under notary project. The governance.md should be placed under `.github` repo as notary project level governance doc.

**Comment by yizha1** [comment]
I will vote for option 1 as well. Now we have 5 out of 9 [MAINTAINERS](https://github.com/notaryproject/.github/blob/main/MAINTAINERS) vote for option 1. We can make decision on Mar 20 community call.

**Comment by yizha1** [comment]
What I am going to do is:

1. Create a PR in `.github` to copy the below doc from `notary` repo to `.github` repo
    - https://github.com/notaryproject/notary/blob/master/CODE_OF_CONDUCT.md
    - https://github.com/notaryproject/notary/blob/master/CONTRIBUTING.md
    - https://github.com/notaryproject/notary/blob/master/PROJECTS
2. Create a new PR in `.github` to address the amendment
3. After the above two PRs are merged, create a PR in `notary` repo to remove the three documents.

**Comment by iamsamirzon** [comment]
LGTM

**Comment by yizha1** [comment]
Updates:
- One issue was created to remove governance doc in `notary` repo. https://github.com/notaryproject/notary/issues/1672

**Comment by yizha1** [comment]
@toddysm this PR https://github.com/notaryproject/.github/pull/17, which was merged yesterday. The next step is to create a PR in `notary` repo to remove the gov docs after `notary` sub-project maintainers are aligned.
