### ISSUE TITLE
Install Codecov to Notary Project org

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/.github#72]
## Pain point

Code coverage is not updated for the `main` branch of `notation`, `notation-go`, `notation-core-go` repos since 2 months ago and thus the code coverage badge is not accurate.

## RCA
Codecov requires token to upload code coverage in `v4` (`v3` stopped working)

## Proposal
Install Codecov to Notary Project org to obtain the codecov token.

## Requested Permissions
![image](https://github.com/notaryproject/.github/assets/32161882/8e89de0a-a9e5-4819-83f4-b02df27d8864)

## Related Issues
- https://github.com/notaryproject/notation/issues/921

## Related PRs
- https://github.com/notaryproject/notation/pull/920
- https://github.com/notaryproject/notation-core-go/pull/199

## Actions
Please respond **LGTM** or **REJECT** (with reasoning).

**Comment by yizha1** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by toddysm** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Got 4 votes. I've installed the Codecov app on to the Notary Project org.
