### ISSUE TITLE
Proposal for changing the schedule of Thursday's community meetings

### ISSUE THREAD

**Issue by toddysm** [notaryproject/.github#76]
On several occasions, we discovered that Thursday's meetings are cancelled due to lack of agenda or lack of attendance. @vaninrao10, @whalelines, @kipz and I discussed this in one or two of the Thrusday's meetings and would like to propose to change the meeting schedule to the second Thursday of the month and have it once a month.

Having in mind that Monday's meetings happen regularly and cover tactical details and releases, we believe that this is a reasonable schedule. The goal of the Thursday's meeting should be to cover more strategic discussions, involvement with other communities and projects, reviewing the progress of the projects, etc.

Please add comments to this proposal or +1 if you agree with it.

**Comment by FeynmanZhou** [comment]
+1. We can dynamically adjust the meeting cadence based on the community engagement in different time zones

**Comment by whalelines** [comment]
+1

**Comment by kipz** [comment]
+1

**Comment by shizhMSFT** [comment]
+1

**Comment by yizha1** [comment]
+1

**Comment by priteshbandi** [comment]
+1

**Comment by vaninrao10** [comment]
+1. As per our discussion this is the right step to be taken.

**Comment by toddysm** [comment]
@FeynmanZhou having in mind that we have majority agreement to change the schedule, would you mind updating the CNCF calendar and the Zoom invite to update the Thursday schedule to the second Thursday of the month starting August 2024?

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou having in mind that we have majority agreement to change the schedule, would you mind updating the CNCF calendar and the Zoom invite to update the Thursday schedule to the second Thursday of the month starting August 2024?

@notaryproject/notaryproject-org-maintainers  The meeting invitation has been updated. I also raised a [ticket](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2381) to CNCF to request corresponding changes on the CNCF Calendar. Will keep you informed once CNCF replied and updated their calendar.

**Comment by FeynmanZhou** [comment]
Circling back to this issue: CNCF updated the Notary Project monthly meeting on their calendar in July. We could close this issue as completed.
![image](https://github.com/user-attachments/assets/47a29d4e-1715-4664-a5e9-195831741213)
